### PR TITLE
Startup rework

### LINKED ISSUE #1094: LOOT fails to update loadorder when run through MO2 command line
## The problem:
LOOT fails to update loadorder when run through the command line.

## Details
I am using MO2 version 2.2.2.1 archive version, downloaded from Nexus SSE page.

I'm trying to automate the running of LOOT by executing it through MO2 on the command line and ran into the following issue. 

If I run LOOT through MO2 on the command line, using something akin to `<path/to>ModOrganizer.exe -p Default <path/to>LOOT.exe`, it would appear to work at first. LOOT would open up and show me my MO2 plugins, and I can sort and apply fine. After I hit the "Apply" button, I can see in the MO2 folder that `profiles/Default/plugins.txt` got updated with the expected changes. _However_, once I close LOOT, the changes to `plugins.txt` gets reverted back to what it used to be.

Whereas, if I open MO2 and run LOOT by manually navigating the GUI, this behavior doesn't happen. After I close LOOT, `plugins.txt` remains the newly updated list, and `loadorder.txt` gets updated as expected.

LOOT seems to only care about `plugins.txt` and seems to be doing the right thing. This looks like an MO2 bug where MO2 is failing to perform some postprocess functionality consistently between the gui-launch case and the cli-launch case.

Please let me know if it seems to be user error on my part or if there's a work around at this time. Thanks!

### PR DESCRIPTION
**Pull request by isanae**
This is a rework of how MO starts and processes the command line. The goal was to separate startup into initializing `OrganizerCore`, plugins, etc. and showing the main window so commands could be executed in between. It also moves handling of external messages to `MOApplication`.

I've also implemented the `run` command, which works for programs, files and executables, and I've added `reload-plugin` and `refresh`.

A `Command` now has four hooks: 
  - `runEarly()`: called as soon as MO starts;
  - `runPostApplication()`: called after `MOApplication` has been created and Qt initialized;
  - `runPostMultiProcess()`: after the primary instance check is done; and
  - `runPostOrganizer()`: after MO has initialized, but before the UI is shown.

Any hook can return something to exit immediately.

Commands can also specify that they can be forwarded to the primary instance, such as `reload-plugin`, by returning `true` in `canForwardToPrimary()`. There's no notion of forward-only commands, which could be useful for `reload-plugin` and `refresh` because they don't make sense if there's no process currently running. Right now, MO starts up normally and they execute correctly, but they're useless. I decided to not give errors in this case just to simplify things.

I've also simplified the interface for `Command` by removing a few functions and putting everything in `Meta`, including the usage string and an optional `more` description (used by `run` only right now). I had two separate commands `exe` and `run` before, but I've merged them and added `-e` to specify an executable.

I also had to move a bunch of stuff to member variables in `MOApplication` because of the new, two-phase startup: they were local variables in `run()`, but now they're created in `setup()` and used later in `run()`. I've changed `InstanceManager::currentInstance()` to return a `unique_ptr` instead of an `optional` because it makes more sense to hold the former as a member variable imo.

This means that some of the code has moved back to `main()`, which now has the main loop and command line handling.

I also fixed `MessageDialog`, it's sometimes called with a null pointer because `activeWindow()` is used, but it's null when the window doesn't have focus, such as when clicking a download link in the browser. And there's a better error message when running a program with a non-existing current directory.

---

The last commit fixes #1094 by waiting for refreshing to complete when running programs from the command line. I've also added `--logs` to duplicate logs to stdout, `-i` with no arguments to output the current instance and made `run -e` do a second, case insensitive lookup for the name (`run -r loot` now works).

I've also removed a call to `refreshDirectoryStructure()` in `OrganizerCore::afterRun()`. It used to be called twice in a row, but that could never work. It's likely to be the source of the constant `can't refresh, already in progress` error in the logs.

I also changed `OrganizerProxy::waitForApplication()` to wait for the refresh so plugins won't have a stale view after running something and asking for a refresh.

Needs https://github.com/ModOrganizer2/modorganizer-uibase/pull/109.

### CODE REVIEW

**Review by Holt59 — APPROVED** [review]

File: src/loglist.cpp [hunk 1]
```diff
@@ -311,6 +317,21 @@ void qtLogCallback(
   }
 }
 
+void logToStdout(bool b)
```
Comment (Holt59) [inline src/loglist.cpp:320]: Does this log to stdout only or causes it to log to UI + log file + stdout? (+ whatever... )

Comment (isanae) [reply src/loglist.cpp:320]: Logs everywhere. There's actually already a sink set up in uibase for the console, it's just never useful because MO is not a console application, so stdout doesn't go anywhere. All this does is connect stdout to the parent process' console, or create one.

**Review by Al12rs — APPROVED** [review]

**Review by Holt59 — APPROVED** [review]
