### PR TITLE
Prevent crash when opening NXM link before selecting instance

### LINKED ISSUE #2121: Starting download via NXM with no instance crashes MO2.
## The problem:
When a download is started via the Nexus without an instance of MO2 having been selected (e.g., sitting on the instance manager), MO2 crashes.

## To Reproduce:

1. Associate MO2 with NXM links.
2. Start MO2 with the `--pick` option.
3. Start any NXM download from Nexus.
4. MO2 should crash.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.5.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10.0.19045 x64

## Details:
* I realize BG3 isn't a supported game, but that's not the problem here - it just happened to be the one that I first noticed the issue with. Skyrim SE NXM links do the same thing.
* Tangentially related: <https://github.com/ModOrganizer2/modorganizer/issues/1531>

### USVFS:
N/A

### MO Interface:
* <https://gist.github.com/tim-elmer/a2ff50299121f6ec15d74acf60b7e547>

### PR DESCRIPTION
**Pull request by JonathanFeenstra**
Fixes #2121. Implementing #1531 would be more complicated, since we'd have to consider more edge cases (e.g. what to do when there are multiple instances found for the game from the downloaded mod).

### CODE REVIEW

File: src/moapplication.cpp [hunk 1]
```diff
@@ -390,8 +390,14 @@ void MOApplication::externalMessage(const QString& message)
       }
     }
   } else if (isNxmLink(message)) {
-    MessageDialog::showMessage(tr("Download started"), qApp->activeWindow(), false);
-    m_core->downloadRequestedNXM(message);
+    if (InstanceManager::singleton().currentInstance()->gamePlugin() == nullptr) {
+      // This can happen if MO2 is started with the --pick option and no instance has
+      // been selected yet, in which case m_core will be null.
+      reportError(tr("No instance has been selected. Cannot download mod."));
```
Comment (Holt59) [inline src/moapplication.cpp:396]: Can you change the message to something along `"You need to select an instance before trying to download mods."`, I think it'd be better.

Comment (JonathanFeenstra) [reply src/moapplication.cpp:396]:
```suggestion
      reportError(tr("You need to select an instance before trying to download mods."));
```
